#ifndef ERRORNUMBER_H
#define ERRORNUMBER_H

//MAIN

#define PORT_RANGE_ERROR 11

//NETSERVICE
#define SOCKET_ERROR 21
#define BIND_ERROR 22
//RECIEVER

#define SELECT_REPEAT_ERROR 31
#define THREAD_MEMORY_ERROR_REC 32
#define THREAD_CREATION_ERROR_REC 33

//MESSAGEHANDLER
#define THREAD_MEMORY_ERROR_MSG 41
#define THREAD_CREATION_ERROR_MSG 42

//SENDER
#define THREAD_MEMORY_ERROR_SEN 51
#define THREAD_CREATION_ERROR_SEN 52

#endif // ERRORNUMBER_H
